"""
Test Dynamic Question Generation
Tests the GROQ-powered question generation endpoint
"""

import requests
import json

BASE_URL = "http://localhost:5000"

def test_generate_all_questions():
    """Test generating questions for all domains"""
    print("\n" + "="*60)
    print("TEST: Generate Questions for All Domains")
    print("="*60)
    
    response = requests.post(f"{BASE_URL}/clinical/generate-questions", json={})
    
    print(f"\nStatus Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        print(f"\nSuccess: {data.get('success')}")
        print(f"Generated by: {data.get('generated_by')}")
        
        questions = data.get('questions', {})
        for domain, qs in questions.items():
            print(f"\n{domain.upper()} ({len(qs)} questions):")
            for i, q in enumerate(qs, 1):
                print(f"  {i}. {q}")
    else:
        print(f"Error: {response.text}")


def test_generate_specific_domain():
    """Test generating questions for a specific domain"""
    print("\n" + "="*60)
    print("TEST: Generate Questions for Cognitive Domain Only")
    print("="*60)
    
    response = requests.post(
        f"{BASE_URL}/clinical/generate-questions",
        json={"domain": "cognitive"}
    )
    
    print(f"\nStatus Code: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        questions = data.get('questions', {})
        
        if 'cognitive' in questions:
            print(f"\nCOGNITIVE QUESTIONS ({len(questions['cognitive'])} questions):")
            for i, q in enumerate(questions['cognitive'], 1):
                print(f"  {i}. {q}")
    else:
        print(f"Error: {response.text}")


def test_multiple_generations():
    """Test that each generation produces unique questions"""
    print("\n" + "="*60)
    print("TEST: Multiple Generations (Should be Different)")
    print("="*60)
    
    print("\nGeneration 1:")
    response1 = requests.post(
        f"{BASE_URL}/clinical/generate-questions",
        json={"domain": "motoric"}
    )
    
    if response1.status_code == 200:
        questions1 = response1.json().get('questions', {}).get('motoric', [])
        for i, q in enumerate(questions1, 1):
            print(f"  {i}. {q}")
    
    print("\nGeneration 2:")
    response2 = requests.post(
        f"{BASE_URL}/clinical/generate-questions",
        json={"domain": "motoric"}
    )
    
    if response2.status_code == 200:
        questions2 = response2.json().get('questions', {}).get('motoric', [])
        for i, q in enumerate(questions2, 1):
            print(f"  {i}. {q}")
    
    # Check if questions are different
    if questions1 and questions2:
        same_count = sum(1 for q1, q2 in zip(questions1, questions2) if q1 == q2)
        print(f"\nSame questions: {same_count}/4")
        print(f"Different questions: {4-same_count}/4")


if __name__ == "__main__":
    print("\n🧪 DYNAMIC QUESTION GENERATION TESTS")
    print("="*60)
    
    try:
        # Test 1: Generate all questions
        test_generate_all_questions()
        
        # Test 2: Generate specific domain
        test_generate_specific_domain()
        
        # Test 3: Multiple generations
        test_multiple_generations()
        
        print("\n✅ All tests completed!")
        
    except requests.exceptions.ConnectionError:
        print("\n❌ ERROR: Cannot connect to Flask server")
        print("   Make sure the server is running on http://localhost:5000")
    except Exception as e:
        print(f"\n❌ ERROR: {str(e)}")
